services:
  fastapi_test_app:
    build:
      context: .
    container_name: fastapi_test_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres_db_test
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  postgres_db_test:
    image: postgres:16
    container_name: quick_meat_db_test
#    env_file:
#      - src/.test.env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES_DB}"
    ports:
      - "5432:5432"