services:
  fastapi_test_app:
    build:
      context: .
    container_name: fastapi_test_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres_db_test
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  postgres_db_test:
    image: postgres:16
    container_name: quick_meat_db_test
    env_file:
      - src/.test.env
    environment:
      POSTGRES_USER: admin_test
      POSTGRES_PASSWORD: admin_password_test
      POSTGRES_DB: quick_meat_db_test
    ports:
      - "5432:5432"