services:
  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  postgres_db:
    image: postgres:16
    container_name: quick_meat_db
    env_file:
      - src/.env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES_DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d quick_meat_db" ]
      timeout: 30s
      interval: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: