services:
  fastapi_test_app:
    build:
      context: .
    container_name: fastapi_test_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres_db_test
    env_file:
      - src/.test.env
    environment:
      APP_CONFIG__MIDD__CORS_ALLOWED_ORIGINS: '["http://localhost", "http://localhost:8080"]'
      APP_CONFIG__DB__POSTGRES_USER: admin_test
      APP_CONFIG__DB__POSTGRES_PASSWORD: admin_password_test
      APP_CONFIG__DB__POSTGRES_HOST: postgres_db_test
      APP_CONFIG__DB__POSTGRES_PORT: 5432
      APP_CONFIG__DB__POSTGRES_DB: quick_meat_db_test
      APP_CONFIG__DB__ECHO: "False"
      APP_CONFIG__AUTH_JWT__ACCESS_TOKEN_EXPIRE_DAY: 1
      APP_CONFIG__AUTH_JWT__REFRESH_TOKEN_EXPIRE_DAY: 15
      APP_CONFIG__AUTH_JWT__ALGORITHM: RS256
      APP_CONFIG__MODE: TEST
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  postgres_db_test:
    image: postgres:16
    container_name: quick_meat_db_test
    env_file:
      - src/.test.env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES_DB}"
    ports:
      - "5432:5432"