name: CI - Test

on:
  push:
    branches: ["main"]  # Запуск тестів при пуші в гілку main

jobs:
  test:
    runs-on: ubuntu-latest  # Використовуємо останню версію Ubuntu для тестування

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Крок для клонування репозиторію

      - name: Create Docker test network
        run: docker network create test_network

      - name: Start Postgres container
        run: |
          docker run -d \
          --name postgres_db_test \
          --network test_network \
          -e POSTGRES_USER=admin_test \
          -e POSTGRES_PASSWORD=admin_password_test \
          -e POSTGRES_DB=quick_meat_db_test \
          -p 5432:5432 \
          postgres:16

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
        env:
          PGPASSWORD: admin_password_test

      - name: Build FastAPI container
        run: |
          docker build -t fastapi_test_app .

      - name: Start FastAPI container
        run: |
          docker run -d \
            --name fastapi_test_app \
            --network test_network \
            -p 8000:8000 \
            fastapi_test_app \

      - name: Check container status
        run: docker ps -a

      - name: Run tests in FastAPI container
        run: docker exec fastapi_test_app pytest -s -vv
