name: CI - Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start service
      run: |
        docker-compose -f docker-compose.test.yml --env-file src/.test.env up --build -d

    - name: Check PostgreSQL readiness
      run: |
        for i in {1..5}; do
          if docker exec quick_meat_db_test pg_isready -U admin_test; then
            echo "Postgres is ready"
            break
          fi
          echo "Waiting for Postgres..."
          sleep 3
        done

    - name: Check FastAPI is running
      run: |
        for i in {1..5}; do
          if curl -s http://localhost:8000; then
            echo "FastAPI is ready"
            break
          fi
          echo "Waiting for FastAPI..."
          sleep 3
        done

    - name: Run tests
      run: |
        docker-compose -f docker-compose.test.yml exec -T fastapi_test_app pytest -s -vvv

    - name: Stop service
      if: always()
      run: |
        docker-compose -f docker-compose.test.yml down