name: CI - Test

on:
  push:
    branches: ["main"]  # Запуск тестів при пуші в гілку main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2

#    - name: Copy .test.env to .env
#      run: cp src/.test.env .env

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start Docker Compose services
      run: |
        docker-compose -f docker-compose.yml --env-file src/.env up --build -d

    - name: Check container status
      run: docker ps

    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec quick_meat_db_test pg_isready -U admin_test; do
          echo "Waiting for postgres to be ready..."
          sleep 5
        done

    - name: Show files in app container
      run: docker exec fastapi_test_app ls

    - name: check env
      run: docker-compose -f docker-compose.yml exec -T fastapi_test_app env

    - name: logs fastapi_test_app container status
      run: docker logs fastapi_test_app

    - name: Check FastAPI is running
      run: |
        until curl -s http://localhost:8000; do
          echo "Waiting for FastAPI to be ready..."
          sleep 2
        done

#    - name: Run tests
#      run: |
#        docker-compose -f docker-compose.yml exec -T fastapi_test_app pytest -s -vvv

    - name: Tear down Docker Compose services
      if: always()
      run: |
        docker-compose -f docker-compose.yml down