name: CI - Test

on:
  push:
    branches: ["main"]  # Запуск тестів при пуші в гілку main

jobs:
  test:
    runs-on: ubuntu-latest  # Використовуємо останню версію Ubuntu для тестування

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Крок для клонування репозиторію

      - name: Create Docker test network
        run: docker network create test_network
